{{- if .Values.redisSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: data-proxy-redis
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.redisSecret.password | quote }}
  password: {{ .Values.redisSecret.password | quote }}
  REDIS_READ: {{ printf "redis://:%s@data-proxy-valkey.data-proxy.svc.cluster.local:6379/1" .Values.redisSecret.password | quote }}
  REDIS_WRITE: {{ printf "redis://:%s@data-proxy-valkey-0.data-proxy-valkey-headless.data-proxy.svc.cluster.local:6379/0" .Values.redisSecret.password | quote }}
  REDIS: {{ printf "{\"read\":\"redis://:%s@data-proxy-valkey:6379/1\",\"write\":\"redis://:%s@data-proxy-valkey:6379/0\"}" .Values.redisSecret.password .Values.redisSecret.password | quote }}
{{- end }}
