FROM docker.io/golang:1.27.1-alpine AS builder

RUN apk add --no-cache git=2.54.0-r0 && go install go.k6.io/xk6/cmd/xk6@v1.4.12

WORKDIR /build

RUN xk6 build --with github.com/grafana/xk6-kubernetes@v0.12.0 -o /build/k6

FROM docker.io/alpine:3.23.5

RUN adduser -D -u 10001 k6

COPY --from=builder /build/k6 /usr/local/bin/k6

USER k6

ENTRYPOINT ["k6", "run"]
