FROM pgduckdb/pgduckdb:17-v1.1.1

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    postgresql-17-postgis-3 \
    curl && \
  python3 -m venv /opt/patroni && \
  /opt/patroni/bin/pip install --no-cache-dir "patroni[kubernetes]" && \
  ln -s /opt/patroni/bin/patroni /usr/local/bin/patroni && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

USER postgres
