FROM docker.io/pgduckdb/pgduckdb:17-v1.1.1

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl=7.88.1-10+deb12u15 \
    postgresql-17-postgis-3=3.6.4+dfsg-2.pgdg12+1 \
    python3=3.11.2-1+b1 \
    python3-pip=23.0.1+dfsg-1 \
    python3-venv=3.11.2-1+b1 && \
  python3 -m venv /opt/patroni && \
  /opt/patroni/bin/pip install --no-cache-dir "patroni[kubernetes,psycopg3]" kubernetes && \
  ln -s /opt/patroni/bin/patroni /usr/local/bin/patroni && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

USER postgres
