FROM docker.io/library/alpine:3.20@sha256:c64c687cbea9300178b30c95835354e34c4e4febc4badfe27102879de0483b5e

RUN apk add --no-cache nginx nginx-mod-http-js \
 && mkdir -p /run/nginx

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/build/fallback.js /etc/nginx/fallback.js

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
