FROM ghcr.io/nushell/nushell:0.113.0-alpine

USER root

RUN apk add --no-cache openssl=3.5.8-r0

ADD https://github.com/cablehead/http-nu/releases/download/v0.17.2/http-nu-v0.17.2-linux-amd64.tar.gz /tmp/http-nu.tar.gz
RUN tar xzf /tmp/http-nu.tar.gz -C /usr/local/bin/ --strip-components=1 && rm /tmp/http-nu.tar.gz

COPY scripts/oidc.nu /scripts/oidc.nu
COPY scripts/oidc.nuon /config/oidc.nuon
COPY scripts/oidc.pem /config/oidc.pem

USER nushell

EXPOSE 8080

ENTRYPOINT []
CMD ["http-nu", "0.0.0.0:8080", "/scripts/oidc.nu"]
