{{- if and .Values.ingress.enabled .Values.ingress.auth.enabled }}
{{- $policyWriters := list }}
{{- range $schema, $_ := (.Values.syncConfig.schemas | default dict) }}
{{- $policyWriters = append $policyWriters (printf "data-proxy.policy_writer.%s" $schema) }}
{{- end }}
{{- $parties := concat (.Values.ingress.auth.authorizedParties | default list) $policyWriters }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "data-proxy.fullname" . }}-postgrest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "data-proxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgrest
  action: ALLOW
  rules:
    - from:
        - source:
            requestPrincipals:
              - "*"
      {{- with $parties }}
      when:
        - key: request.auth.claims[azp]
          values:
            {{- toYaml . | nindent 12 }}
      {{- end }}
{{- end }}
