{{- if not .Values.ha.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
data:
  nginx.conf: |
{{ include "data-proxy.nginxProxyConfig" . | indent 4 }}
{{- end }}
