{{- $root := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-schema-writers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: sync
data:
  writers.json: |
    {
      "writers": {
    {{- $schemas := keys .Values.syncConfig.schemas | sortAlpha }}
    {{- range $index, $schema := $schemas }}
      {{ $schema | quote }}: {{ include "data-proxy.schemaWriterDsn" (dict "root" $root "schema" $schema) | quote }}{{ if lt (add1 $index) (len $schemas) }},{{ end }}
    {{- end }}
      }
    }
