apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
data:
  sync.json: |
    {{ .Values.sync.config | toJson | nindent 4 }}
