{{- if .Values.ha.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.pgbouncerRwName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |
    {{ include "data-proxy.pgbouncerRwConfig" . | nindent 4 }}
{{- end }}
