{{- if .Values.ha.enabled }}
{{- $root := . }}
{{- range $schema, $_ := (default $root.Values.cnpg.schemas $root.Values.syncConfig.schemas) }}
{{- $cluster := include "data-proxy.cnpgClusterName" (dict "root" $root "schema" $schema) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" $root }}-{{ $schema | replace "_" "-" }}-nginx-proxy
  namespace: {{ $root.Release.Namespace }}
data:
  nginx.conf: |
{{ $root.Files.Get "files/nginx.conf" | replace "__PGRST_MAP__" (printf "map $http_accept_profile $postgrest_read { default \"http://%s-postgrest-ro.%s.svc.cluster.local:3000\"; } map $http_accept_profile $postgrest_write { default \"http://%s-postgrest-rw.%s.svc.cluster.local:3000\"; }" $cluster $root.Release.Namespace $cluster $root.Release.Namespace) | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" $root }}-{{ $schema | replace "_" "-" }}-webdis
  namespace: {{ $root.Release.Namespace }}
data:
  webdis-write.json: |
{{ include "data-proxy.webdisWriteConfig" $root | indent 4 }}
  webdis-read.json: |
{{ include "data-proxy.webdisReadConfig" $root | indent 4 }}
{{- end }}
{{- end }}
