{{- if or .Values.jobs.maintenance.enabled .Values.jobs.backup.enabled .Values.sync.recovery.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
data:
  maintenance.nu: |
{{ .Files.Get "files/maintenance.nu" | nindent 4 }}
  backup.nu: |
{{ .Files.Get "files/backup.nu" | nindent 4 }}
  lib.nu: |
{{ .Files.Get "files/lib.nu" | nindent 4 }}
  recover-workflows.nu: |
{{ .Files.Get "files/recover-workflows.nu" | nindent 4 }}
  wait-for-postgres.nu: |
{{ .Files.Get "files/wait-for-postgres.nu" | nindent 4 }}
{{- range $path, $_ := .Files.Glob "files/templates/*.sql" }}
  {{ base $path }}: |
{{ $.Files.Get $path | nindent 4 }}
{{- end }}
{{- range $path, $_ := .Files.Glob "files/templates/**/*.sql" }}
  {{ base (dir $path) }}_{{ base $path }}: |
{{ $.Files.Get $path | nindent 4 }}
{{- end }}
{{- end }}
