{{- if .Values.fallback.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
data:
  nginx.conf: |
{{ include "data-proxy.nginxProxyConfig" . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-webdis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: webdis
data:
  webdis.json: |
{{ include "data-proxy.webdisConfig" . | indent 4 }}
{{- end }}
