apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-proxy.fullname" . }}-db-migrate
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: db-migrate
data:
  01_extensions.sql: |
    {{ .Files.Get "db/01_extensions.sql" | nindent 4 }}
  02_roles.sh: |
    {{ include "data-proxy.rolesScript" . | nindent 4 }}
  03_pre_request.sql: |
    {{ include "data-proxy.preRequestSql" . | nindent 4 }}
  04_access_policy.sql: |
    {{ include "data-proxy.accessPolicySql" . | nindent 4 }}
