apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-proxy.fullname" . }}-dumper
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: dumper
spec:
  replicas: 0
  selector:
    matchLabels:
      {{- include "data-proxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dumper
  template:
    metadata:
      labels:
        {{- include "data-proxy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dumper
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.dumper.terminationGracePeriodSeconds }}
      topologySpreadConstraints:
        {{- toYaml .Values.dumper.topologySpreadConstraints | nindent 8 }}
      serviceAccountName: {{ include "data-proxy.serviceAccountName" . }}
      containers:
        - name: dumper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "dp.sync.dumper"]
          env:
            {{- include "data-proxy.appEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "data-proxy.syncConfigVolumeMount" . | nindent 12 }}
            {{- include "data-proxy.gcpVolumeMount" . | nindent 12 }}
      volumes:
        {{- include "data-proxy.syncConfigVolume" . | nindent 8 }}
        {{- include "data-proxy.gcpVolume" . | nindent 8 }}
