{{- if .Values.swaggerUi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-proxy.fullname" . }}-swagger-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "data-proxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: swagger-ui
  template:
    metadata:
      labels:
        {{- include "data-proxy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: swagger-ui
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: swagger-ui
          image: {{ .Values.swaggerUi.image }}
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: swagger-ui-initializer
              mountPath: /usr/share/nginx/html/swagger-initializer.js
              subPath: swagger-initializer.js
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: swagger-ui-initializer
          configMap:
            name: {{ include "data-proxy.fullname" . }}-swagger-ui-initializer
{{- end }}
