apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-proxy.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "data-proxy.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "data-proxy.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "data-proxy.serviceAccountName" . }}
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "dp.sync.worker"]
          env:
            {{- include "data-proxy.appEnv" . | nindent 12 }}
          volumeMounts:
            {{- include "data-proxy.syncConfigVolumeMount" . | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- include "data-proxy.syncConfigVolume" . | nindent 8 }}
