{{- if .Values.ha.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "data-proxy.fullname" . }}-patroni
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps, endpoints, pods]
    verbs: [get, list, watch, create, update, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "data-proxy.fullname" . }}-patroni
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "data-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "data-proxy.fullname" . }}-patroni
  apiGroup: rbac.authorization.k8s.io
{{- end }}
