{{- if .Values.ha.enabled }}
{{- $root := . }}
{{- range $schema, $_ := (default $root.Values.cnpg.schemas $root.Values.syncConfig.schemas) }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "data-proxy.fullname" $root }}-{{ $schema | replace "_" "-" }}-proxy
  namespace: {{ $root.Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "data-proxy.fullname" $root }}-{{ $schema | replace "_" "-" }}-proxy
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: {{ $root.Values.fallback.autoscaling.minReplicaCount }}
  maxReplicaCount: {{ $root.Values.fallback.autoscaling.maxReplicaCount }}
  pollingInterval: {{ $root.Values.fallback.autoscaling.pollingInterval }}
  cooldownPeriod: {{ $root.Values.fallback.autoscaling.cooldownPeriod }}
  triggers:
{{ include "data-proxy.haTriggers" (dict "root" $root "schema" $schema "component" "fallback") | nindent 4 }}
{{- end }}
{{- end }}
