{{- if not .Values.ha.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "data-proxy.fullname" . }}-nginx-proxy
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    name: {{ include "data-proxy.fullname" . }}-nginx-proxy
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: 1
  maxReplicaCount: {{ .Values.fallback.autoscaling.maxReplicaCount }}
  pollingInterval: {{ .Values.fallback.autoscaling.pollingInterval }}
  cooldownPeriod: {{ .Values.fallback.autoscaling.cooldownPeriod }}
  triggers:
{{- if gt (len (.Values.fallback.autoscaling.triggers | default list)) 0 }}
{{ toYaml .Values.fallback.autoscaling.triggers | nindent 4 }}
{{- else }}
{{ include "data-proxy.defaultResourceTriggers" . | nindent 4 }}
{{- end }}
{{- end }}
