{{- $root := . }}
{{- $authenticatorName := printf "%s-cnpg-authenticator" (include "data-proxy.fullname" $root) }}
{{- $authenticator := lookup "v1" "Secret" $root.Release.Namespace $authenticatorName }}
{{- $authenticatorPassword := randAlphaNum 32 }}
{{- if $authenticator }}
{{- $authenticatorPassword = index $authenticator.data "password" | b64dec }}
{{- end }}
{{- if not $root.Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $authenticatorName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" $root | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $root.Values.auth.authenticatorRole | quote }}
  password: {{ $authenticatorPassword | quote }}
{{- end }}
---
{{- $poolerName := printf "%s-cnpg-pooler" (include "data-proxy.fullname" $root) }}
{{- $pooler := lookup "v1" "Secret" $root.Release.Namespace $poolerName }}
{{- $poolerPassword := randAlphaNum 32 }}
{{- if $pooler }}
{{- $poolerPassword = index $pooler.data "password" | b64dec }}
{{- end }}
{{- if not $root.Values.cnpg.pooler.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $poolerName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" $root | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: cnpg_pooler_pgbouncer
  password: {{ $poolerPassword | quote }}
{{- end }}
