{{- if not .Values.pgduckdb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.pgduckdb.password | quote }}
  PGRST_AUTHENTICATOR_PASSWORD: {{ .Values.pgduckdb.authenticatorPassword | quote }}
  {{- if .Values.ha.enabled }}
  PATRONI_REPLICATION_PASSWORD: {{ .Values.ha.patroni.replicationPassword | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.backup.enabled (not .Values.backup.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  BACKUP_PASSWORD: {{ .Values.backup.password | quote }}
{{- end }}
---
{{- if not .Values.gcs.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-gcs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  GCS_KEY_ID: {{ .Values.gcs.keyId | quote }}
  GCS_SECRET_KEY: {{ .Values.gcs.secretKey | quote }}
{{- end }}

