{{- if not .Values.duckdb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.duckdb.password | quote }}
  PGRST_AUTHENTICATOR_PASSWORD: {{ .Values.duckdb.authenticatorPassword | quote }}
  {{- if .Values.ha.enabled }}
  PATRONI_REPLICATION_PASSWORD: {{ .Values.ha.patroni.replicationPassword | quote }}
  {{- end }}
{{- end }}
---
{{- if not .Values.gcs.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-gcs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  GCS_KEY_ID: {{ .Values.gcs.keyId | quote }}
  GCS_SECRET_KEY: {{ .Values.gcs.secretKey | quote }}
{{- end }}
---
{{- if not .Values.postgrest.existingJwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGRST_JWT_SECRET: {{ .Values.postgrest.jwtSecret | quote }}
{{- end }}
