{{- $root := . }}
{{- $authenticatorName := printf "%s-cnpg-authenticator" (include "data-proxy.fullname" $root) }}
{{- $authenticator := lookup "v1" "Secret" $root.Release.Namespace $authenticatorName }}
{{- $authenticatorPassword := randAlphaNum 32 }}
{{- if $authenticator }}
{{- $authenticatorPassword = index $authenticator.data "password" | b64dec }}
{{- end }}
{{- if not $root.Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $authenticatorName }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" $root | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $root.Values.auth.authenticatorRole | quote }}
  password: {{ $authenticatorPassword | quote }}
{{- end }}
