{{- if .Values.ha.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-proxy.fullname" . }}-pgbouncer-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  userlist.txt: |
    {{ include "data-proxy.pgbouncerUserlist" . | nindent 4 }}
{{- end }}
