{{- if .Values.ha.enabled }}
{{- $root := . }}
{{- range $schema, $_ := (default $root.Values.cnpg.schemas $root.Values.syncConfig.schemas) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-proxy.fullname" $root }}-{{ $schema | replace "_" "-" }}-nginx-proxy
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" $root | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
    data-proxy.io/schema: {{ $schema | quote }}
spec:
  selector:
    {{- include "data-proxy.selectorLabels" $root | nindent 4 }}
    app.kubernetes.io/component: nginx-proxy
    data-proxy.io/schema: {{ $schema | quote }}
  ports:
    - name: http
      port: 8080
      targetPort: http
{{- end }}
{{- end }}
