apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-proxy.fullname" . }}-duckdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: duckdb
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "data-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: duckdb
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
