{{- if .Values.ha.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-proxy.masterServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: duckdb
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "data-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: duckdb
    role: master
{{- end }}
