apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-proxy.fullname" . }}-postgrest
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
spec:
  type: ClusterIP
  selector:
    {{- include "data-proxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgrest
  ports:
    - name: http
      port: 3000
      targetPort: http
