{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "data-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ingress.gateway }}
  hosts:
    - {{ .Values.ingress.host | quote }}
  http:
    - route:
        - destination:
            host: {{ include "data-proxy.fullname" . }}-postgrest
            port:
              number: 3000
{{- end }}
