{{- if .Values.ingress.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "data-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-proxy.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ingress.gateway }}
  hosts:
    - {{ .Values.ingress.host | quote }}
  http:
    {{- if .Values.swaggerUi.enabled }}
    - match:
        - uri:
            prefix: /docs
      route:
        - destination:
            host: {{ include "data-proxy.fullname" . }}-swagger-ui
            port:
              number: 8080
    {{- end }}
    - route:
        - destination:
            host: {{ include "data-proxy.fullname" . }}-postgrest
            port:
              number: 3000
      {{- with .Values.ingress.timeout }}
      timeout: {{ . }}
      {{- end }}
      {{- if gt (int .Values.ingress.retries.attempts) 0 }}
      retries:
        attempts: {{ .Values.ingress.retries.attempts }}
        {{- with .Values.ingress.retries.perTryTimeout }}
        perTryTimeout: {{ . }}
        {{- end }}
        {{- with .Values.ingress.retries.retryOn }}
        retryOn: {{ . | quote }}
        {{- end }}
      {{- end }}
{{- end }}
