apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-proxy-k6
  namespace: data-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-proxy-k6
  namespace: data-proxy
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-proxy-k6
  namespace: data-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-proxy-k6
subjects:
  - kind: ServiceAccount
    name: data-proxy-k6
    namespace: data-proxy
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: data-proxy-e2e
  namespace: data-proxy
spec:
  parallelism: 1
  script:
    configMap:
      name: data-proxy-e2e
      file: e2e.ts
  runner:
    image: localhost/k6:local
    serviceAccountName: data-proxy-k6
    automountServiceAccountToken: "true"
    env:
      - name: BASE_URL
        value: http://istio-ingressgateway.istio-ingress.svc.cluster.local
      - name: API_HOST
        value: data-proxy.local
      - name: WEBDIS_URL
        value: http://webdis.data-proxy.svc.cluster.local:7379
      - name: NAMESPACE
        value: data-proxy
      - name: PRODUCER_CRONJOB
        value: data-proxy-producer
