apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-proxy-k6
  namespace: data-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-proxy-k6
  namespace: data-proxy
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-proxy-k6
  namespace: data-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-proxy-k6
subjects:
  - kind: ServiceAccount
    name: data-proxy-k6
    namespace: data-proxy
---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: data-proxy-perf
  namespace: data-proxy
spec:
  parallelism: 1
  script:
    configMap:
      name: data-proxy-k6
      file: perf.ts
  runner:
    image: localhost/k6:local
    serviceAccountName: data-proxy-k6
    automountServiceAccountToken: "true"
    env:
      - name: BASE_URL
        value: http://istio-ingressgateway.istio-ingress.svc.cluster.local
      - name: API_HOST
        value: data-proxy.local
      - name: OIDC_TOKEN_URL
        value: http://keycloak.keycloak.svc.cluster.local:8080/realms/dev/protocol/openid-connect/token
      - name: OIDC_USER_CLIENT_ID
        value: user
      - name: OIDC_NO_POLICY_CLIENT_ID
        value: no_policy
      - name: OIDC_POLICY_WRITER_CLIENT_ID
        value: policy_writer
      - name: OIDC_CLIENT_SECRET
        value: test-secret
      - name: K6_PROFILE
        value: load
      - name: HA_MODE
        value: "false"
