apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: data-proxy-perf
  namespace: data-proxy
spec:
  parallelism: 1
  paused: "false"
  script:
    configMap:
      name: data-proxy-k6
      file: perf.ts
  runner:
    image: registry.localhost:5001/k6:local
    serviceAccountName: manifests-k6-perf
    automountServiceAccountToken: "true"
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "3"
        memory: 4Gi
    env:
      - name: BASE_URL
        value: http://istio-ingressgateway.istio-ingress.svc.cluster.local
      - name: API_HOST
        value: data-proxy.local
      - name: OIDC_TOKEN_URL
        value: http://keycloak.keycloak.svc.cluster.local:8080/realms/dev/protocol/openid-connect/token
      - name: OIDC_USER_CLIENT_ID
        value: user
      - name: OIDC_NO_POLICY_CLIENT_ID
        value: no_policy
      - name: OIDC_POLICY_WRITER_CLIENT_ID
        value: policy_writer
      - name: OIDC_CLIENT_SECRET
        value: test-secret
      - name: K6_PROFILE
        value: load
      - name: HA_MODE
        value: "false"
