name: Setup devenv
description: Install Nix and devenv with Magic Nix Cache
runs:
  using: composite
  steps:
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Install devenv
      shell: bash
      run: nix profile add nixpkgs#devenv
