sync:
  image: gcr.io/proj/data-proxy-sync:1.0.0
  imagePullPolicy: IfNotPresent
  schedule: "0 2 * * *"
  config:
    schemas:
      test:
        claim: preferred_username
        tables:
          - name: rj-ia-desenvolvimento.dev.full_table
            strategy: full
            rls:
              - column: unit_id
                unit_type: unit

ducklake:
  litestream:
    storage:
      storageClass: standard
  readerCatalog:
    storage:
      storageClass: standard

cnpg:
  db:
    name: data-proxy
    user: admin
  instances: 2
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: "4"
      memory: 4Gi

s3:
  bucket: prod-bucket

postgrest:
  proxyUri: https://api.example.com
  jwtSecret: '{"kty":"RSA","e":"AQAB","alg":"RS256","n":"abc123"}'
  replicas: 1
  resources: {}
  autoscaling:
    minReplicaCount: 1
    maxReplicaCount: 3
    pollingInterval: 30
    cooldownPeriod: 300
    triggers: []

redis:
  existingSecret: data-proxy-redis
  writerAddress: redis-writer:6379
  webdisHost: redis-writer
  webdisPort: 6379

auth:
  anonRole: anon
  userRole: user
  authenticatorRole: postgrest
  jwtRoleClaim: $.role
  rlsSchema: rls

ingress:
  enabled: true
  gateway: "istio-system/istio-gateway"
  host: "data-proxy.example.com"

seaweedfs:
  s3:
    createBuckets:
      - name: prod-bucket
