name: Release image

on:
  push:
    tags:
      - app-v*
      - pgduckdb-v*
      - patroni-v*

permissions:
  contents: read
  packages: write

jobs:
  app:
    if: startsWith(github.ref_name, 'app-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: type=match,pattern=app-v(.*),group=1
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  pgduckdb:
    if: startsWith(github.ref_name, 'pgduckdb-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-pgduckdb
          tags: type=match,pattern=pgduckdb-v(.*),group=1
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.pgduckdb
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  patroni:
    if: startsWith(github.ref_name, 'patroni-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}-patroni
          tags: type=match,pattern=patroni-v(.*),group=1
      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.patroni
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
